"""
Multi-layer AI & document-integrity analysis for PDF, Word, and images.

Layers: embedded metadata, raw binary string scan, document structure, visible content,
and tamper indicators. Metadata can be stripped — deeper checks catch many AI exports.
"""
from __future__ import annotations

import io
import re
import zipfile
import xml.etree.ElementTree as ET
from datetime import datetime, timezone
from typing import Any

import fitz

# (regex, severity, human label)
_AI_PATTERNS: list[tuple[re.Pattern[str], str, str]] = [
    (re.compile(r"chat\s*gpt|chatgpt", re.I), "high", "ChatGPT"),
    (re.compile(r"\bopenai\b", re.I), "high", "OpenAI"),
    (re.compile(r"\bclaude\b|\banthropic\b", re.I), "high", "Claude / Anthropic"),
    (re.compile(r"\bgemini\b|\bbard\b|\bgoogle\s*ai\b|\bnotebooklm\b", re.I), "high", "Google Gemini"),
    (re.compile(r"\bcopilot\b|\bmicrosoft\s+copilot\b", re.I), "high", "Microsoft Copilot"),
    (re.compile(r"dall[\s\-]?e|dalle", re.I), "high", "DALL·E"),
    (re.compile(r"\bmidjourney\b", re.I), "high", "Midjourney"),
    (re.compile(r"stable\s*diffusion|stablediffusion|\bsd\s*xl\b|\bcomfyui\b", re.I), "high", "Stable Diffusion"),
    (re.compile(r"\bautomatic1111\b|\ba1111\b", re.I), "high", "ComfyUI / A1111"),
    (re.compile(r"\badobe\s*firefly\b|\bfirefly\b", re.I), "high", "Adobe Firefly"),
    (re.compile(r"\bleonardo\.?ai\b|\bideogram\b|\bflux\.?1\b|\bblack\s*forest\b", re.I), "medium", "Image AI generator"),
    (re.compile(r"\bcanva\b.*\bai\b|\bmagic\s*write\b", re.I), "medium", "Canva AI"),
    (re.compile(r"\bjasper\b|\bnotion\s*ai\b|\bperplexity\b|\bgrok\b|\bdeepseek\b", re.I), "medium", "Writing AI"),
    (re.compile(r"\bgamma\.?app\b|\bbeautiful\.?ai\b|\btome\.?app\b|\bslidesai\b", re.I), "medium", "AI slide/document platform"),
    (re.compile(r"\bai[\s\-_]?generated\b|\bsynthetic\s+media\b|\bgen\s*ai\b", re.I), "medium", "AI-generated claim"),
    (re.compile(r"\bcontent\s*credentials\b|\bc2pa\b|\bclaim_generator\b|\bjumbf\b", re.I), "high", "Content Credentials (C2PA)"),
    (re.compile(r"\bgpt[\s\-_]?\d|\bgpt-4|\bo1[\s\-]preview\b", re.I), "high", "GPT model reference"),
    (re.compile(r"\bllama\b|\bmistral\b|\bphi[\s\-]?\d\b", re.I), "medium", "Open-weights LLM"),
    # Programmatic PDF pipelines (common for AI-authored exports and server-side generators)
    (re.compile(r"reportlab", re.I), "high", "ReportLab PDF generator"),
    (re.compile(r"\bfpdf2?\b|\bpyfpdf\b", re.I), "high", "FPDF programmatic PDF"),
    (re.compile(r"\bpdfkit\b|\bwkhtmltopdf\b|\bdocraptor\b|\bpdfcrowd\b", re.I), "high", "HTML-to-PDF pipeline"),
    (re.compile(r"\bpdf[\s\-]?lib\b|\bpuppeteer\b|\bplaywright\b", re.I), "high", "Headless browser PDF export"),
    (re.compile(r"\bprince\s*xml\b|\bprince\b", re.I), "medium", "Prince XML PDF engine"),
    (re.compile(r"\b(itext|mpdf|tcpdf|pikepdf|borb|pypdf)\b", re.I), "high", "Programmatic PDF library"),
    (re.compile(r"\bpython[\s\-]?docx\b|\bdocx2pdf\b|\bhtmldocx\b", re.I), "high", "Python document automation"),
    (re.compile(r"\bweasyprint\b|\bcairo\s*pdf\b", re.I), "medium", "Web/CSS PDF renderer"),
    (re.compile(r"\btypst\b|\btectonic\b|\bpandoc\b", re.I), "medium", "Markup-to-PDF toolchain"),
    (re.compile(r"\bmellivora\b|\bpdfsam\b|\bqpdf\b", re.I), "low", "PDF manipulation tool"),
]

_CONTENT_AI_PHRASES: list[tuple[re.Pattern[str], str, str]] = [
    (re.compile(r"as an ai(?:\s+language)?\s+model", re.I), "high", "AI self-identification in body text"),
    (re.compile(r"i(?:'m| am) an? ai\b", re.I), "high", "AI self-identification in body text"),
    (re.compile(r"language model(?:\s+developed|\s+created)?\s+by", re.I), "high", "LLM attribution in body text"),
    (re.compile(r"i(?:'m| am) (?:unable|not able) to (?:access|browse)", re.I), "medium", "Typical chatbot disclaimer"),
    (re.compile(r"hope this helps|let me know if you(?:'d| would) like", re.I), "medium", "Chatbot closing phrase"),
    (re.compile(r"here(?:'s| is) a (?:draft|sample|template|letter|document)", re.I), "medium", "AI draft introduction"),
    (re.compile(r"certainly!|of course!|absolutely!", re.I), "low", "Chatbot affirmation tone"),
    (re.compile(r"generated by (?:artificial intelligence|an? ai)", re.I), "high", "AI generation statement in text"),
    (re.compile(r"\bregenerate\b.*\bresponse\b", re.I), "medium", "Chat UI language in document"),
]

_PRINT_EXPORT_PRODUCERS = re.compile(
    r"skia/pdf|chrome|chromium|quartz pdfcontext|microsoft.*print|"
    r"cups|safari|wkhtmltopdf|cairo|weasyprint|puppeteer|headless|mozilla",
    re.I,
)

_PROGRAMMATIC_PRODUCERS = re.compile(
    r"reportlab|fpdf|pdfkit|prince|mpdf|tcpdf|itext|pypdf|pikepdf|borb|"
    r"typst|tectonic|pandoc|docraptor|pdfcrowd|weasyprint|mellivora",
    re.I,
)

_PLACEHOLDER_META = re.compile(r"^\(unspecified\)$|^\(anonymous\)$|^untitled\s+document$", re.I)

_ZERO_WIDTH_RE = re.compile(r"[\u200b\u200c\u200d\u2060\ufeff]")

_BROWSER_ONLY_PRODUCER = re.compile(
    r"^(?:macos|windows).*pdf|pdfium|mozilla|firefox",
    re.I,
)

_AI_IMAGE_SIZES = frozenset({
    (1024, 1024), (512, 512), (768, 768), (1024, 768), (768, 1024),
    (1536, 1024), (1024, 1536), (1792, 1024), (1024, 1792), (2048, 2048),
})

_SEVERITY_RANK = {"high": 3, "medium": 2, "low": 1}

_DISCLAIMER = (
    "This report combines metadata, binary string search, structure analysis, and visible "
    "content heuristics. Sophisticated fraud may still evade detection; stripped metadata "
    "and human-edited AI text reduce certainty. Use as a risk signal alongside human review — "
    "not as sole legal proof of origin or authenticity."
)

_DOCX_NS = {
    "cp": "http://schemas.openxmlformats.org/package/2006/metadata/core-properties",
    "dc": "http://purl.org/dc/elements/1.1/",
    "dcterms": "http://purl.org/dc/terms/",
    "ep": "http://schemas.openxmlformats.org/officeDocument/2006/extended-properties",
    "w": "http://schemas.openxmlformats.org/wordprocessingml/2006/main",
}


def _signal(
    *,
    field: str,
    value: str,
    source: str,
    indicator: str,
    severity: str,
    note: str,
    category: str = "metadata",
) -> dict[str, Any]:
    return {
        "field": field,
        "value": (value or "")[:500],
        "source": source,
        "indicator": indicator,
        "severity": severity,
        "note": note,
        "category": category,
    }


def _scan_text(text: str, *, field: str, source: str, category: str = "metadata") -> list[dict[str, Any]]:
    if not text or not str(text).strip():
        return []
    raw = str(text).strip()
    hits: list[dict[str, Any]] = []
    seen: set[str] = set()
    for pattern, severity, label in _AI_PATTERNS:
        if pattern.search(raw):
            key = f"{field}:{label}"
            if key in seen:
                continue
            seen.add(key)
            hits.append(_signal(
                field=field, value=raw, source=source, indicator=label,
                severity=severity, note=f"Matched AI-related pattern in {field}", category=category,
            ))
    return hits


def _scan_content_phrases(text: str, *, source: str) -> list[dict[str, Any]]:
    if not text or len(text.strip()) < 20:
        return []
    raw = text.strip()
    hits: list[dict[str, Any]] = []
    seen: set[str] = set()
    for pattern, severity, label in _CONTENT_AI_PHRASES:
        m = pattern.search(raw)
        if m:
            key = label
            if key in seen:
                continue
            seen.add(key)
            start = max(0, m.start() - 40)
            excerpt = raw[start:m.end() + 60].replace("\n", " ")
            hits.append(_signal(
                field="document body", value=excerpt, source=source,
                indicator=label, severity=severity,
                note="AI-style phrasing found in visible document text", category="content",
            ))
    return hits


def _scan_key_values(pairs: list[tuple[str, str]], source: str, category: str = "metadata") -> list[dict[str, Any]]:
    signals: list[dict[str, Any]] = []
    for field, value in pairs:
        signals.extend(_scan_text(value, field=field, source=source, category=category))
    return signals


def _scan_binary(data: bytes, *, source: str) -> list[dict[str, Any]]:
    """Search entire file bytes for AI tool strings (survives stripped Info dict)."""
    signals: list[dict[str, Any]] = []
    seen: set[str] = set()
    try:
        text = data.decode("latin-1", errors="ignore")
    except Exception:
        return signals
    for pattern, severity, label in _AI_PATTERNS:
        for m in pattern.finditer(text):
            key = f"{label}:{m.start()}"
            if label in seen:
                continue
            seen.add(label)
            ctx = text[max(0, m.start() - 30):m.end() + 50].replace("\x00", " ")
            signals.append(_signal(
                field="raw file bytes", value=ctx, source=source,
                indicator=label, severity=severity,
                note="AI tool signature found in embedded binary/string data (not just Info header)",
                category="binary",
            ))
            break
    return signals


def _verdict_from_signals(signals: list[dict[str, Any]]) -> tuple[str, str, str]:
    if not signals:
        return (
            "no_signals",
            "low",
            "No AI or integrity risk signals detected across metadata, content, structure, and binary scans.",
        )
    max_rank = max(_SEVERITY_RANK.get(s.get("severity", "low"), 1) for s in signals)
    high = sum(1 for s in signals if s.get("severity") == "high")
    medium = sum(1 for s in signals if s.get("severity") == "medium")
    cats = {s.get("category") for s in signals}
    multi_layer = len(cats) >= 2

    if max_rank >= 3 or high >= 2 or (high >= 1 and multi_layer):
        return (
            "likely_ai",
            "high" if high >= 1 else "medium",
            f"Found {len(signals)} risk signal(s) across {len(cats)} check layer(s) "
            f"({high} strong, {medium} moderate) — review before trusting this document.",
        )
    if max_rank >= 3 or high >= 1:
        return (
            "likely_ai",
            "high" if high else "medium",
            f"Found {len(signals)} signal(s) suggesting AI involvement or suspicious origin.",
        )
    if max_rank >= 2 or len(signals) >= 2 or multi_layer:
        return (
            "possible_ai",
            "medium",
            f"Found {len(signals)} moderate signal(s); document may be AI-assisted, exported from chat, or altered.",
        )
    return (
        "possible_ai",
        "low",
        "Weak or indirect hints only — treat as inconclusive.",
    )


def _pdf_structure_forensics(doc: fitz.Document, data: bytes, meta: dict) -> list[dict[str, Any]]:
    signals: list[dict[str, Any]] = []
    eof_count = data.count(b"%%EOF")
    if eof_count > 1:
        signals.append(_signal(
            field="PDF structure", value=f"{eof_count} %%EOF markers",
            source="pdf_structure", indicator="Incremental save / revision history",
            severity="medium", category="tamper",
            note="Multiple PDF revisions often indicate post-creation editing or re-export",
        ))

    if b"/JavaScript" in data or b"/JS" in data:
        signals.append(_signal(
            field="PDF structure", value="JavaScript action present",
            source="pdf_structure", indicator="Embedded JavaScript",
            severity="medium", category="tamper",
            note="Scripts can alter appearance or exfiltrate data — verify source",
        ))

    producer = (meta.get("producer") or "").strip()
    creator = (meta.get("creator") or "").strip()
    author = (meta.get("author") or "").strip()
    title = (meta.get("title") or "").strip()

    if producer and _PROGRAMMATIC_PRODUCERS.search(producer):
        signals.append(_signal(
            field="Producer", value=producer, source="pdf_structure",
            indicator="Programmatic PDF library",
            severity="high", category="structure",
            note="Built by code (ReportLab, FPDF, iText, etc.) — typical of AI document pipelines, not hand-authored Word exports",
        ))
    elif producer and _PRINT_EXPORT_PRODUCERS.search(producer):
        signals.append(_signal(
            field="Producer", value=producer, source="pdf_structure",
            indicator="Browser or print-to-PDF export",
            severity="medium", category="structure",
            note="Often used to export AI chat answers or web pages to PDF (metadata usually stripped)",
        ))
    elif producer and _BROWSER_ONLY_PRODUCER.search(producer):
        signals.append(_signal(
            field="Producer", value=producer, source="pdf_structure",
            indicator="System PDF printer",
            severity="low", category="structure",
            note="May indicate print/save from browser rather than native Word/InDesign authoring",
        ))

    if creator and _PRINT_EXPORT_PRODUCERS.search(creator):
        signals.append(_signal(
            field="Creator", value=creator, source="pdf_structure",
            indicator="Browser user-agent as creator",
            severity="medium", category="structure",
            note="Creator field contains a browser string — common when printing ChatGPT, Google Docs, or web apps to PDF",
        ))

    placeholder_fields = [
        (k, v) for k, v in (("creator", creator), ("author", author), ("title", title))
        if v and _PLACEHOLDER_META.search(v)
    ]
    if placeholder_fields and (producer or creator):
        signals.append(_signal(
            field=placeholder_fields[0][0], value=placeholder_fields[0][1], source="pdf_structure",
            indicator="Placeholder metadata values",
            severity="medium", category="structure",
            note="Generic placeholders like (unspecified) or Untitled document — common in automated/AI exports",
        ))

    if not producer and not creator and len(doc) > 0:
        signals.append(_signal(
            field="PDF Info", value="Empty Creator and Producer",
            source="pdf_structure", indicator="Stripped authoring metadata",
            severity="medium", category="structure",
            note="Professional documents usually retain authoring software; empty fields suggest re-export or sanitisation",
        ))

    raster_pages = 0
    for i in range(len(doc)):
        page = doc[i]
        text = (page.get_text() or "").strip()
        images = page.get_images(full=True)
        if images and len(text) < 120:
            raster_pages += 1
            if len(text) < 40:
                signals.append(_signal(
                    field=f"Page {i + 1}", value=f"{len(images)} image(s), {len(text)} text chars",
                    source="pdf_structure", indicator="Raster-heavy page (screenshot-style)",
                    severity="medium", category="structure",
                    note="Full-page image with little selectable text — common when saving AI chat or scanned exports",
                ))

    if raster_pages == len(doc) and len(doc) > 0:
        signals.append(_signal(
            field="All pages", value=f"{len(doc)} raster-dominant page(s)",
            source="pdf_structure", indicator="Image-only PDF",
            severity="high", category="structure",
            note="Entire document appears to be images — text may not be authentically authored in Word/PDF",
        ))

    return signals


def _pdf_content_forensics(doc: fitz.Document) -> tuple[list[dict[str, Any]], str]:
    signals: list[dict[str, Any]] = []
    chunks: list[str] = []
    zw_pages = 0
    for i in range(min(len(doc), 20)):
        text = doc[i].get_text() or ""
        if text.strip():
            chunks.append(text)
            signals.extend(_scan_content_phrases(text, source=f"pdf_page_{i + 1}"))
            if _ZERO_WIDTH_RE.search(text):
                zw_pages += 1
                signals.append(_signal(
                    field=f"Page {i + 1}", value="Invisible Unicode (zero-width) characters",
                    source=f"pdf_page_{i + 1}", indicator="Zero-width Unicode in body text",
                    severity="medium", category="content",
                    note="Hidden characters often survive AI copy-paste from ChatGPT, Gemini, or Google Docs",
                ))
    if zw_pages >= 2:
        signals.append(_signal(
            field="Multiple pages", value=f"{zw_pages} page(s) with zero-width characters",
            source="pdf_content", indicator="Repeated invisible Unicode",
            severity="high", category="content",
            note="Multiple pages contain hidden Unicode — strong sign of AI/web copy-paste rather than native authoring",
        ))
    full = "\n".join(chunks)
    return signals, full[:8000]


def _extract_pdf(data: bytes) -> dict[str, Any]:
    checks = ["pdf_info", "pdf_xmp", "pdf_binary", "pdf_structure", "pdf_content"]
    signals: list[dict[str, Any]] = []
    standard: dict[str, str] = {}
    xmp_raw = ""

    signals.extend(_scan_binary(data, source="pdf_binary"))

    body_excerpt = ""
    doc = fitz.open(stream=data, filetype="pdf")
    try:
        meta = doc.metadata or {}
        for key in ("format", "title", "author", "subject", "keywords", "creator", "producer", "creationDate", "modDate"):
            val = (meta.get(key) or "").strip()
            if val:
                standard[key] = val
        pairs = [(k, v) for k, v in standard.items() if k not in ("format", "creationDate", "modDate")]
        signals.extend(_scan_key_values(pairs, "pdf_info"))

        try:
            xmp_raw = doc.get_xml_metadata() or ""
        except Exception:
            xmp_raw = ""
        if xmp_raw:
            checks.append("pdf_xmp_parsed")
            signals.extend(_scan_text(xmp_raw, field="XMP", source="pdf_xmp"))
            for tag in ("dc:creator", "xmp:CreatorTool", "pdf:Producer", "xmp:MetadataDate"):
                m = re.search(rf"<{tag}[^>]*>([^<]+)</", xmp_raw, re.I)
                if m:
                    signals.extend(_scan_text(m.group(1), field=tag, source="pdf_xmp"))

        signals.extend(_pdf_structure_forensics(doc, data, meta))
        content_signals, body_excerpt = _pdf_content_forensics(doc)
        signals.extend(content_signals)
    finally:
        doc.close()

    return {
        "file_type": "pdf",
        "checks_performed": checks,
        "metadata": {
            "standard": standard,
            "xmp_excerpt": xmp_raw[:4000] if xmp_raw else None,
            "body_excerpt": body_excerpt if body_excerpt else None,
        },
        "signals": _dedupe_signals(signals),
    }


def _dedupe_signals(signals: list[dict[str, Any]]) -> list[dict[str, Any]]:
    seen: set[str] = set()
    out: list[dict[str, Any]] = []
    for s in signals:
        key = f"{s.get('category')}:{s.get('indicator')}:{s.get('field')}:{s.get('value', '')[:80]}"
        if key in seen:
            continue
        seen.add(key)
        out.append(s)
    return out


def _xml_text(el: ET.Element | None) -> str:
    if el is None:
        return ""
    return "".join(el.itertext()).strip()


def _extract_docx(data: bytes) -> dict[str, Any]:
    checks = ["docx_core", "docx_app", "docx_binary", "docx_content"]
    signals: list[dict[str, Any]] = []
    standard: dict[str, str] = {}
    body_excerpt = ""

    signals.extend(_scan_binary(data, source="docx_binary"))

    with zipfile.ZipFile(io.BytesIO(data)) as zf:
        names = set(zf.namelist())
        if "docProps/core.xml" in names:
            root = ET.fromstring(zf.read("docProps/core.xml"))
            mapping = {
                "title": _xml_text(root.find("dc:title", _DOCX_NS)),
                "subject": _xml_text(root.find("dc:subject", _DOCX_NS)),
                "creator": _xml_text(root.find("dc:creator", _DOCX_NS)),
                "description": _xml_text(root.find("dc:description", _DOCX_NS)),
                "keywords": _xml_text(root.find("cp:keywords", _DOCX_NS)),
                "lastModifiedBy": _xml_text(root.find("cp:lastModifiedBy", _DOCX_NS)),
                "category": _xml_text(root.find("cp:category", _DOCX_NS)),
            }
            for k, v in mapping.items():
                if v:
                    standard[k] = v
            signals.extend(_scan_key_values(list(mapping.items()), "docx_core"))

        if "docProps/app.xml" in names:
            root = ET.fromstring(zf.read("docProps/app.xml"))
            app_fields = {
                "Application": _xml_text(root.find("ep:Application", _DOCX_NS)),
                "AppVersion": _xml_text(root.find("ep:AppVersion", _DOCX_NS)),
                "Company": _xml_text(root.find("ep:Company", _DOCX_NS)),
                "Manager": _xml_text(root.find("ep:Manager", _DOCX_NS)),
            }
            for k, v in app_fields.items():
                if v:
                    standard[k] = v
            signals.extend(_scan_key_values(list(app_fields.items()), "docx_app"))

        if "docProps/custom.xml" in names:
            checks.append("docx_custom")
            custom_xml = zf.read("docProps/custom.xml").decode("utf-8", errors="replace")
            signals.extend(_scan_text(custom_xml, field="custom properties", source="docx_custom"))

        if "word/document.xml" in names:
            checks.append("docx_body")
            doc_xml = zf.read("word/document.xml").decode("utf-8", errors="replace")
            body_text = re.sub(r"<[^>]+>", " ", doc_xml)
            body_text = re.sub(r"\s+", " ", body_text).strip()
            body_excerpt = body_text[:8000]
            signals.extend(_scan_content_phrases(body_text, source="docx_body"))

    return {
        "file_type": "docx",
        "checks_performed": checks,
        "metadata": {"standard": standard, "body_excerpt": body_excerpt or None},
        "signals": _dedupe_signals(signals),
    }


def _extract_image(data: bytes, filename: str) -> dict[str, Any]:
    from PIL import Image

    checks = ["image_format", "image_exif", "image_binary"]
    signals: list[dict[str, Any]] = []
    standard: dict[str, str] = {}
    exif_map: dict[str, str] = {}

    signals.extend(_scan_binary(data, source="image_binary"))

    img = Image.open(io.BytesIO(data))
    try:
        standard["format"] = img.format or ""
        standard["mode"] = img.mode or ""
        w, h = img.size if img.size else (0, 0)
        if w and h:
            standard["dimensions"] = f"{w}×{h}"
            if (w, h) in _AI_IMAGE_SIZES:
                signals.append(_signal(
                    field="dimensions", value=f"{w}×{h}", source="image_forensic",
                    indicator="Common AI image resolution",
                    severity="low", category="structure",
                    note="Many generators default to square or standard aspect ratios (weak signal alone)",
                ))

        exif = img.getexif()
        if exif:
            from PIL.ExifTags import TAGS
            for tag_id, val in exif.items():
                tag = TAGS.get(tag_id, str(tag_id))
                if val is None:
                    continue
                text = str(val).strip()
                if text:
                    exif_map[tag] = text[:500]
            signals.extend(_scan_key_values(list(exif_map.items()), "exif"))
        elif img.format in ("JPEG", "WEBP"):
            signals.append(_signal(
                field="EXIF", value="No EXIF block", source="image_forensic",
                indicator="Missing camera/software EXIF",
                severity="low", category="structure",
                note="AI-generated images often lack camera EXIF (common on social downloads too)",
            ))

        if hasattr(img, "info") and img.info:
            checks.append("image_info")
            for key, val in img.info.items():
                if isinstance(val, (bytes, bytearray)):
                    try:
                        text = val.decode("utf-8", errors="replace")
                    except Exception:
                        continue
                else:
                    text = str(val)
                if key.lower() in ("parameters", "comment", "description", "software", "author", "title"):
                    standard[key] = text[:500]
                    signals.extend(_scan_text(text, field=key, source="image_info"))
                elif len(text) < 8000 and re.search(r"steps|sampler|cfg\s*scale|negative\s*prompt", text, re.I):
                    standard[key] = text[:500]
                    signals.append(_signal(
                        field=key, value=text[:500], source="image_info",
                        indicator="Stable Diffusion parameters",
                        severity="high", category="binary",
                        note="Diffusion model generation parameters embedded in image file",
                    ))

        if hasattr(img, "applist"):
            for _app, content in (img.applist or []):
                if b"http://ns.adobe.com" in content or b"xmp" in content.lower():
                    checks.append("image_xmp")
                    try:
                        xmp_text = content.decode("utf-8", errors="replace")
                        signals.extend(_scan_text(xmp_text, field="XMP", source="image_xmp"))
                    except Exception:
                        pass
    finally:
        img.close()

    return {
        "file_type": "image",
        "checks_performed": checks,
        "metadata": {"standard": standard, "exif": exif_map},
        "signals": _dedupe_signals(signals),
    }


def detect_file_kind(data: bytes, filename: str, content_type: str = "") -> str:
    name = (filename or "").lower()
    ct = (content_type or "").lower()
    if data[:4] == b"%PDF" or name.endswith(".pdf") or ct == "application/pdf":
        return "pdf"
    if data[:2] == b"PK" and (name.endswith((".docx", ".doc")) or "wordprocessingml" in ct):
        return "docx"
    if name.endswith(".docx"):
        return "docx"
    image_ext = (".png", ".jpg", ".jpeg", ".webp", ".gif", ".tif", ".tiff", ".bmp")
    if name.endswith(image_ext) or ct.startswith("image/"):
        return "image"
    if data[:8] == b"\x89PNG\r\n\x1a\n" or data[:2] == b"\xff\xd8" or data[:4] == b"RIFF":
        return "image"
    return "unknown"


def analyze_ai_metadata(data: bytes, filename: str = "", content_type: str = "") -> dict[str, Any]:
    if not data:
        raise ValueError("Empty file")
    kind = detect_file_kind(data, filename, content_type)
    if kind == "pdf":
        core = _extract_pdf(data)
    elif kind == "docx":
        core = _extract_docx(data)
    elif kind == "image":
        core = _extract_image(data, filename)
    else:
        raise ValueError("Unsupported file — upload a PDF, Word (.docx), or image (PNG, JPEG, WebP)")

    signals = core.get("signals") or []
    verdict, confidence, summary = _verdict_from_signals(signals)
    categories = sorted({s.get("category", "metadata") for s in signals})

    return {
        "filename": filename or "document",
        "file_type": core["file_type"],
        "verdict": verdict,
        "confidence": confidence,
        "summary": summary,
        "signal_count": len(signals),
        "signals": signals,
        "risk_categories": categories,
        "metadata": core.get("metadata") or {},
        "checks_performed": core.get("checks_performed") or [],
        "disclaimer": _DISCLAIMER,
        "scanned_at": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC"),
    }


def build_report_pdf(report: dict[str, Any]) -> bytes:
    """Render scan results as a downloadable PDF report."""
    doc = fitz.open()
    page = doc.new_page(width=595, height=842)
    margin = 50
    y = 56
    width = 495

    def ensure_space(need: float = 40) -> None:
        nonlocal page, y
        if y + need > 790:
            page = doc.new_page(width=595, height=842)
            y = 56

    def write(text: str, *, size: float = 10, bold: bool = False, gap: float = 4) -> None:
        nonlocal y
        ensure_space(size + gap + 8)
        safe = (text or "").replace("—", "-").replace("·", "-")
        page.insert_text((margin, y), safe, fontsize=size + (1 if bold else 0), fontname="helv")
        y += size + gap

    def write_wrapped(text: str, *, size: float = 9, gap: float = 6) -> None:
        nonlocal y
        words = (text or "").replace("\r", "").split()
        line = ""
        for word in words:
            trial = f"{line} {word}".strip()
            if fitz.get_text_length(trial, fontname="helv", fontsize=size) > width:
                if line:
                    write(line, size=size, gap=2)
                line = word
            else:
                line = trial
        if line:
            write(line, size=size, gap=gap)

    verdict_labels = {
        "likely_ai": "LIKELY AI / HIGH RISK",
        "possible_ai": "POSSIBLE AI / MODERATE RISK",
        "no_signals": "NO STRONG SIGNALS",
        "inconclusive": "INCONCLUSIVE",
    }

    write("CivicSign - AI & Document Integrity Scan", size=14, bold=True, gap=10)
    write(f"File: {report.get('filename', 'document')}", size=10, gap=4)
    write(f"Scanned: {report.get('scanned_at', '')}", size=9, gap=8)
    write(f"Verdict: {verdict_labels.get(report.get('verdict'), report.get('verdict', ''))}", size=11, bold=True, gap=4)
    write(f"Confidence: {report.get('confidence', '')} · Type: {(report.get('file_type') or '').upper()}", size=9, gap=6)
    write_wrapped(report.get("summary") or "", size=9, gap=10)

    write(f"Signals ({report.get('signal_count', 0)})", size=11, bold=True, gap=6)
    signals = report.get("signals") or []
    if not signals:
        write_wrapped("No risk signals detected.", gap=8)
    else:
        for i, s in enumerate(signals[:25], start=1):
            ensure_space(50)
            write(
                f"{i}. [{s.get('severity', '').upper()}] {s.get('indicator', '')} ({s.get('category', '')})",
                size=9, bold=True, gap=2,
            )
            write_wrapped(s.get("note") or "", size=8, gap=2)
            write_wrapped(f"Field: {s.get('field', '')} — {s.get('value', '')[:200]}", size=8, gap=8)

    write("Checks performed", size=11, bold=True, gap=4)
    write_wrapped(" · ".join(report.get("checks_performed") or []), gap=10)

    meta = report.get("metadata") or {}
    if meta.get("standard"):
        write("Document metadata", size=11, bold=True, gap=4)
        for k, v in list(meta["standard"].items())[:12]:
            write_wrapped(f"{k}: {v}", size=8, gap=3)
        y += 4

    write("Disclaimer", size=10, bold=True, gap=4)
    write_wrapped(report.get("disclaimer") or _DISCLAIMER, size=8, gap=4)

    out = doc.tobytes()
    doc.close()
    return out