// Centralised blog post data + helpers. Used as a "static fallback" when the
// /api/blog endpoint hasn't been seeded yet; admin-created posts via the
// internal team panel are merged in on top (API wins on slug conflicts).

import api from "@/lib/api";

export const POSTS = [
  {
    slug: "are-e-signatures-legal-in-the-uk",
    title: "Are electronic signatures legal in the UK in 2026?",
    excerpt: "The short answer is yes, and they have been since the Electronic Communications Act 2000. We walk through eIDAS, the Law Commission's 2019 report, and what actually counts as a valid e-signature on a UK contract.",
    category: "UK Law",
    date: "Feb 14, 2026",
    readTime: "6 min read",
    author: "CivicSign Editorial",
    image: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85",
    body: [
      { type: "p", content: "It's the question we get asked more than any other: are electronic signatures actually legal in the United Kingdom? The honest answer is that they have been legal for more than two decades, and they have been the default for most British businesses for at least the last five years. What's changed in 2026 is not whether they're legal, but how much weight different types of e-signature now carry in the eyes of UK courts, HM Land Registry, the ICO and HMRC." },
      { type: "h2", content: "The short version" },
      { type: "p", content: "Under section 7 of the Electronic Communications Act 2000, an electronic signature is admissible as evidence of authentication in UK court. The UK eIDAS Regulation (the on-shored version that survived Brexit) goes further and recognises three tiers of e-signature: simple, advanced and qualified. For 99% of contracts, a simple electronic signature is sufficient as long as the signing process is auditable and the signatory's intent is clear." },
      { type: "callout", content: "Bottom line: if your e-signature platform captures the signature, the date, the signer's identity (typically email + IP) and produces a tamper-evident audit trail, your signed PDF holds up in a UK court the same way a wet-ink signature does." },
      { type: "h2", content: "The three tiers under UK eIDAS" },
      { type: "ul", content: [
        "Simple Electronic Signature (SES): any data attached to or logically associated with the document that the signer uses to sign. A typed name, drawn signature or click-to-agree all count. UK eIDAS Article 3(11).",
        "Advanced Electronic Signature (AES): uniquely linked to the signer, capable of identifying them, created under their sole control, and detects subsequent changes to the document. UK eIDAS Article 26. On CivicSign, AES is available on Pro (selectable when sending) and is the default on Business, especially when combined with SMS or knowledge-based recipient authentication.",
        "Qualified Electronic Signature (QES): an AES backed by a qualified certificate from a Qualified Trust Service Provider (QTSP). UK eIDAS Article 3(12). Required only for a narrow set of high-value transactions (e.g. some EU cross-border deeds). CivicSign offers QES on request for Business customers via a QTSP partner, contact us to enable it.",
      ]},
      { type: "h3", content: "How CivicSign maps tiers to plans" },
      { type: "ul", content: [
        "Free: electronic signatures with consent, attribution, audit trail and SHA-256 seal (aligned with the Electronic Communications Act 2000).",
        "Pro: SES by default; AES selectable on Review & Send when you need stronger Art. 26 evidence.",
        "Business: AES by default, strengthened with optional SMS/KBA recipient authentication; QES available on request.",
      ]},
      { type: "h2", content: "What the Law Commission said in 2019" },
      { type: "p", content: "The Law Commission's 2019 report on Electronic Execution of Documents was the watershed moment. It confirmed that electronic signatures are valid for documents that are required to be 'in writing' or 'signed' under English law, including most commercial contracts. The Commission also confirmed that deeds can be signed electronically provided the witnessing requirement is satisfied, the witness must see the signatory apply their electronic signature. For property deeds lodged with HM Land Registry, Practice Guide 82 requires the witness to be physically present at the moment of signing, not watching over a video call." },
      { type: "h2", content: "When you still need a wet signature" },
      { type: "p", content: "A handful of UK documents still require a physical wet signature. The list is short and getting shorter every year. As of February 2026 it includes:" },
      { type: "ul", content: [
        "Wills under the Wills Act 1837 (though Law Commission consultation is ongoing).",
        "Certain HM Revenue and Customs documents where HMRC has not yet certified electronic equivalents.",
        "Lasting Powers of Attorney for registration with the Office of the Public Guardian (under review).",
        "A small number of statutory declarations and oaths.",
      ]},
      { type: "h2", content: "What this means for your business" },
      { type: "p", content: "For UK businesses sending NDAs, employment contracts, supplier agreements, engagement letters, tenancy agreements, sales memos, statutory notices, settlement agreements and the like, electronic signatures are not just legal, they are now the expected default. Refusing to accept them in 2026 is increasingly the position that needs defending, not the other way around." },
      { type: "p", content: "What matters in practice is the quality of your audit trail. A signed PDF on its own is not enough. You need: signer identity (email verified), IP address, timestamps for every interaction (sent, viewed, signed), a tamper-evident hash on the final document, and a Certificate of Completion that links it all together. CivicSign includes all of this on every plan, including the free tier, because we think it should be table-stakes." },
      { type: "h2", content: "Further reading" },
      { type: "ul", content: [
        { text: "Law Commission, Electronic execution of documents (2019)", href: "https://www.lawcom.gov.uk/document/electronic-execution-of-documents/" },
        { text: "UK eIDAS Regulation (as on-shored)", href: "https://www.legislation.gov.uk/eur/2014/910/contents" },
        { text: "Electronic Communications Act 2000, section 7", href: "https://www.legislation.gov.uk/ukpga/2000/7/section/7" },
        { text: "Law Society practice note on electronic signatures", href: "https://www.lawsociety.org.uk/topics/business-management/execution-of-a-document-using-and-electronic-signature" },
      ]},
    ],
  },
  {
    slug: "hm-land-registry-electronic-signatures-2026",
    title: "HM Land Registry & electronic signatures: what conveyancers need to know",
    excerpt: "Since July 2020 HM Land Registry has accepted electronic signatures on dispositionary deeds. Here's exactly what your audit trail needs to contain, plus a worked example of an electronically signed TR1.",
    category: "Real Estate",
    date: "Feb 07, 2026",
    readTime: "8 min read",
    author: "CivicSign Editorial",
    image: "https://images.unsplash.com/photo-1560518883-ce09059eeffa",
    body: [
      { type: "p", content: "If you ran a UK conveyancing practice in 2019, the path to completion involved couriers, wet ink and the post box. If you run one in 2026, you can complete a TR1 from your client's kitchen table over a video call. The thing that changed is a single Practice Guide from HM Land Registry, published in July 2020 and refined every year since. This is what you need to know." },
      { type: "h2", content: "Practice Guide 82: conveyancer-certified electronic signatures" },
      { type: "p", content: "HM Land Registry Practice Guide 82 (not Practice Guide 8, which covers execution of deeds generally) sets out the electronic signature methods the Registry accepts. For platform-based signing, what HM Land Registry calls 'conveyancer-certified electronic signatures', the key requirements are:" },
      { type: "ul", content: [
        "All parties must be represented by a conveyancer, with limited exceptions (e.g. lenders on mortgages).",
        "A conveyancer controls the signing process through an established e-signing platform.",
        "Signatories receive a one-time password by text before they can sign.",
        "Where a deed must be witnessed, the witness must be physically present when the signatory applies their electronic signature, video witnessing does not meet Practice Guide 82.",
        "An individually regulated conveyancer lodges a signed certificate confirming the Practice Guide 82 requirements were met.",
      ]},
      { type: "callout", content: "Translation: HM Land Registry does not maintain an approved-provider list. It is you, the conveyancer, who certifies that the platform's process met Practice Guide 82. Choose your platform like you'd choose your indemnity insurer, and keep the platform's audit report on file." },
      { type: "h2", content: "Witnessing requirements" },
      { type: "p", content: "Deeds under English law must be witnessed. While the Law Commission's 2019 report took a broader view of electronic witnessing, HM Land Registry's current Practice Guide 82 is explicit: for conveyancer-certified electronic signatures, the witness must be in the physical presence of the signatory when they apply their signature electronically. Remote video witnessing does not satisfy this requirement for deeds lodged at HM Land Registry." },
      { type: "p", content: "In CivicSign, sequential signing makes this clean. You route the deed to the grantor first, then to the witness immediately after. Both signatures land on the same document, with the same audit trail, and the witness can attest in their own signature block that they observed the grantor sign electronically." },
      { type: "h2", content: "A worked example: signing a TR1 electronically" },
      { type: "p", content: "Here's how a typical TR1 flow looks in practice. You upload the prepared TR1 to your platform. You add four recipients in sequential order:" },
      { type: "ul", content: [
        "Recipient 1: Seller, places signature and date.",
        "Recipient 2: Seller's witness, places witness signature, name, address and occupation.",
        "Recipient 3: Buyer, places signature and date.",
        "Recipient 4: Buyer's witness, places witness signature, name, address and occupation.",
      ]},
      { type: "p", content: "The seller signs first while their witness watches over a video call. The platform routes to the witness, who confirms they observed the act of signing. Then the same flow with the buyer. The final PDF carries all four signatures, four IP addresses, four timestamps and a tamper-evident seal, exactly what Practice Guide 8 expects." },
      { type: "h2", content: "What goes into the conveyancer's certificate" },
      { type: "p", content: "When you lodge the application, an individually regulated conveyancer must provide a certificate in the form set out in Practice Guide 82: 'I certify that, to the best of my knowledge and belief, the applicable requirements set out in practice guide 82 for the use of conveyancer-certified electronic signatures have been satisfied.' The certificate must be dated, signed, name the firm and specify the deed. CivicSign's Certificate of Completion is designed to sit alongside this, it gives the audit trail your certificate references, but the conveyancer certificate itself must be signed by a regulated individual, not delegated to admin staff." },
      { type: "h2", content: "When NOT to use electronic signatures" },
      { type: "p", content: "Practice Guide 82 does not apply to all property documents. Statutory declarations, some Stamp Duty Land Tax forms, and Lasting Powers of Attorney still require wet signatures (the latter pending review). Mercury signing, where wet-ink signature pages are scanned and emailed, is also covered in Practice Guide 82 as a separate method. When in doubt, check the latest version of Practice Guide 82, HM Land Registry updates it regularly, and the trend is consistently towards more digital acceptance, not less." },
      { type: "h2", content: "Practical tips for property practices" },
      { type: "ul", content: [
        "Save your TR1, TR5 and AP1 templates once with fields pre-placed, every transaction takes seconds, not minutes.",
        "Always use sequential signing for deeds, it forces the witness to follow immediately after the signatory.",
        "Confirm signatory identity through the platform's verification process (email plus OTP by text, as Practice Guide 82 expects). Pair ID document checks where your risk policy requires them.",
        "Keep the Certificate of Completion attached to the same case file, your file passes SRA monitoring with no effort.",
      ]},
    ],
  },
  {
    slug: "gift-aid-electronic-declarations-hmrc-guide",
    title: "Gift Aid via e-signature: the HMRC-friendly playbook for UK charities",
    excerpt: "How small charities can capture HMRC-compliant Gift Aid declarations at the door, online or via email, and what fields your audit trail needs to keep your annual return clean.",
    category: "Charities",
    date: "Jan 28, 2026",
    readTime: "5 min read",
    author: "CivicSign Editorial",
    image: "https://images.unsplash.com/photo-1593113598332-cd288d649433",
    body: [
      { type: "p", content: "For every £1 a UK taxpayer donates to a registered charity, HMRC will hand the charity 25p back through Gift Aid. Multiplied across a year's worth of donations, that uplift is the difference between hitting your fundraising target and missing it. Most small charities are leaving that money on the table because their Gift Aid declaration process is stuck in 2008." },
      { type: "h2", content: "What the law says" },
      { type: "p", content: "HMRC's detailed guidance on Gift Aid (Chapter 3 of the Charities guidance) is unambiguous: Gift Aid declarations can be made electronically, by tick-box, online form, email, fax or even text message, provided the declaration contains the required information and you can produce an auditable record if HMRC asks during a compliance review. A signature is not legally required, though many charities still ask for one." },
      { type: "p", content: "The required fields are straightforward:" },
      { type: "ul", content: [
        "Donor's full name (HMRC recommends the donor's full name).",
        "Donor's home address (for UK addresses, house number or name plus postcode is sufficient).",
        "Charity name.",
        "Description of gift(s) the declaration covers (one-off, future and/or past).",
        "Donor's confirmation that they want Gift Aid to apply, plus HMRC's standard wording on their tax liability.",
        "Date of the declaration (recommended, required where the covered period is not otherwise clear).",
      ]},
      { type: "callout", content: "Every CivicSign Gift Aid template includes these fields by default, drop it on a stewarding tablet at an event, or email the link to a regular donor, and you have an HMRC-compliant declaration in seconds." },
      { type: "h2", content: "The compliance audit trail HMRC actually wants" },
      { type: "p", content: "When HMRC opens a compliance review, they want to see two things: that the declaration existed at the time of the donation, and that the donor was identifiable. An electronic Gift Aid declaration handles both more cleanly than a paper one, because it carries an IP address, an email-verified identity and a precise timestamp, none of which a clipboard signature ever did." },
      { type: "p", content: "Keep the Certificate of Completion attached to your donor record. If HMRC ever asks 'how did you capture this declaration?', you can produce the answer in one click, not by digging through a filing cabinet in the church hall." },
      { type: "h2", content: "Where electronic Gift Aid really wins" },
      { type: "ul", content: [
        "At fundraising events: a steward holds a tablet, donor signs, declaration is in your CRM before they reach the buffet.",
        "Online donation flows: pair the donation form with an embedded Gift Aid signing link, conversion goes up because there's no separate paper step.",
        "Annual renewals: bulk-send renewal declarations to lapsed declarants, the ones who never sent the paper back will tap-and-sign on their phone.",
        "Major-donor relationship: bespoke declarations for higher-rate taxpayers feel polished and well-organised, not bureaucratic.",
      ]},
      { type: "h2", content: "Common Gift Aid mistakes" },
      { type: "p", content: "A handful of avoidable mistakes will get a Gift Aid claim rejected:" },
      { type: "ul", content: [
        "Missing the donor's home address. Workplace addresses are not sufficient.",
        "Pre-ticked Gift Aid boxes. The donor must take a positive action to opt in.",
        "Declarations without a date. The date determines when Gift Aid can start being claimed from.",
        "Not telling the donor what to do if they stop being a UK taxpayer or pay less tax in future. Include the standard HMRC wording verbatim.",
      ]},
      { type: "p", content: "If you set up your declaration once in CivicSign with HMRC's verbatim wording, the donor cannot accidentally skip a field. The result: cleaner claims, fewer rejections, and 25% more for your cause." },
    ],
  },
  {
    slug: "right-to-work-digital-checks-uk-hr",
    title: "Digital Right to Work checks: the UK HR playbook",
    excerpt: "Since 2022 UK employers can use certified Identity Service Providers for Right to Work checks. Pair that with an electronically signed declaration and your statutory excuse holds up under inspection.",
    category: "HR & People",
    date: "Jan 21, 2026",
    readTime: "7 min read",
    author: "CivicSign Editorial",
    image: "https://images.unsplash.com/photo-1521737711867-e3b97375f902",
    body: [
      { type: "p", content: "Right to Work checks are the unglamorous bit of British HR that nobody likes doing, and the bit that can cost you up to £45,000 per illegal worker in civil penalties for a first breach (rising to £60,000 for repeat breaches, under the February 2024 code of practice). Since 6 April 2022, employers have been able to use certified Identity Service Providers (IDSPs) to perform digital Right to Work checks on British and Irish citizens. In 2026, relying on photocopied passports alone is increasingly a process problem, not a compliance strategy." },
      { type: "h2", content: "What the Home Office actually accepts" },
      { type: "p", content: "There are now three routes to a compliant Right to Work check, depending on who you're hiring:" },
      { type: "ul", content: [
        "Manual check: in-person inspection of original documents from List A or List B, then a photocopy retained on file with date and signature.",
        "Online Home Office check: using the candidate's share code via the gov.uk service. Available for foreign nationals with current visas.",
        "Digital check via a certified IDSP: for British and Irish citizens holding a valid in-date passport. The IDSP verifies the document and the identity, then provides the employer with a proof of check.",
      ]},
      { type: "callout", content: "The IDSP route is the one most British HR teams should care about, because it removes the need to ever inspect a physical document for a UK or Irish national. The candidate uploads their passport to the IDSP from their phone, the IDSP returns a yes/no, and you keep the proof." },
      { type: "h2", content: "Where electronic signatures fit in" },
      { type: "p", content: "The Home Office does not prescribe a separate 'Right to Work declaration' form, but most employers pair the statutory check with an onboarding pack, employment contract, policies and a candidate attestation confirming the documents they have provided. Historically this was paper. In 2026 it is cleaner as a single electronic signing flow with the IDSP proof of check attached to the same HR file." },
      { type: "p", content: "Your statutory excuse rests on the check itself, manual, online via gov.uk share code, or IDSP, plus clear copies retained for the statutory period. Pairing that with a timestamped electronic contract and attestation gives you one digital file retrievable in one click. Compare that with a paper-only process: photocopies fade, declarations get lost, and your statutory excuse is only as good as the filing cabinet it lives in." },
      { type: "h2", content: "How long do you need to keep the records?" },
      { type: "p", content: "Right to Work check records must be retained for the duration of the worker's employment plus two years after they leave. Failure to produce them on demand from an immigration officer is a sufficient basis for the civil penalty even if the worker did, in fact, have the right to work. The case for digital retention is open and shut." },
      { type: "h2", content: "The CivicSign flow for new starters" },
      { type: "ul", content: [
        "Send the candidate the Right to Work declaration + employment contract in a single signing flow.",
        "Trigger the IDSP check from the candidate's phone in parallel. (We're rolling out integrations with certified providers later in 2026.)",
        "Receive both the signed declaration and the IDSP proof back into the candidate's HR file.",
        "Attach the Certificate of Completion to your single central record entry. Done.",
      ]},
      { type: "h2", content: "Common Right to Work mistakes that bin your statutory excuse" },
      { type: "ul", content: [
        "Photocopying documents without dating and signing the copy.",
        "Accepting a share code on the wrong gov.uk service (visa share codes vs Right to Rent are not the same).",
        "Not re-checking time-limited Right to Work (e.g. when a visa expires), set a calendar reminder, or use a platform that does it for you.",
        "Treating an EU Settled Status share code as a Right to Work share code without the candidate proving status separately.",
      ]},
      { type: "p", content: "Get the basics right, automate the rest, and Right to Work compliance stops being the thing you panic about on the morning of an audit." },
    ],
  },
  {
    slug: "uk-gdpr-vs-eu-gdpr-saas-platforms",
    title: "UK GDPR vs. EU GDPR: what it actually means for your SaaS suppliers",
    excerpt: "Brexit changed less than most vendors will admit. We unpack the practical differences for British businesses choosing a UK-hosted SaaS, and why hosting really does matter for ICO enquiries.",
    category: "Compliance",
    date: "Jan 14, 2026",
    readTime: "9 min read",
    author: "CivicSign Editorial",
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475",
    body: [
      { type: "p", content: "There are two flavours of GDPR in 2026. There's UK GDPR, the on-shored version that lives alongside the Data Protection Act 2018, and there's EU GDPR, which applies inside the EU and to organisations processing EU citizens' data. For most British businesses, the practical difference is small. For SaaS procurement, it's enormous." },
      { type: "h2", content: "The short version" },
      { type: "p", content: "UK GDPR and EU GDPR are still substantively the same regulation. The rights of data subjects, the principles, the lawful bases, all materially identical. The differences are in the supervisory authority (ICO vs the various EU DPAs), the adequacy mechanism between them, and the way each handles international transfers." },
      { type: "h2", content: "Adequacy: the most-asked, least-understood question" },
      { type: "p", content: "The European Commission first granted the UK an adequacy decision in June 2021, which means EU personal data can flow to the UK without needing Standard Contractual Clauses or other transfer safeguards. In December 2025 the Commission renewed both UK adequacy decisions for a further six-year term, now running until 27 December 2031, following its assessment of the UK's Data (Use and Access) Act 2025. A mid-point review is scheduled after four years. Adequacy is not permanent, it depends on the UK maintaining essentially equivalent protections, but the renewal confirms the current framework is holding." },
      { type: "p", content: "From the UK side, the Data Protection (Adequacy) Regulations 2021 named the EEA, Gibraltar and a handful of others as 'adequate'. Transfers from the UK to the EU are therefore unrestricted." },
      { type: "h2", content: "When hosting really matters" },
      { type: "callout", content: "For data subjects whose primary recourse is the ICO, having their data processed inside the UK simplifies everything, the controller, the processor, the regulator and the courts are all subject to the same legal system. There's no 'which supervisor do I write to first' dance." },
      { type: "p", content: "This is the substantive point. If your SaaS supplier processes UK personal data inside the UK, on UK infrastructure, the ICO is the single supervisory authority. If your SaaS supplier processes UK personal data inside the EU or US, the picture gets more complex: you've got at least two supervisory authorities to think about, transfer mechanisms to maintain, and sub-processor disclosures to track." },
      { type: "h2", content: "Sub-processors: the bit nobody reads" },
      { type: "p", content: "Most UK businesses sign a Data Processing Agreement with their SaaS supplier and never look at the sub-processor list. It's worth looking, that list tells you where your data actually lives. A 'UK-based' SaaS that runs on US infrastructure with US support, US ML pipelines and a US payments processor is, for data-residency purposes, primarily a US SaaS." },
      { type: "p", content: "CivicSign's sub-processor list is published openly, kept short, and overwhelmingly UK/EU. We tell you exactly where every byte of your data sits. We think this should be a hygiene-level expectation for any UK SaaS." },
      { type: "h2", content: "International transfers under UK GDPR" },
      { type: "p", content: "If your SaaS supplier needs to transfer UK personal data outside the UK and outside the EEA, they must use an appropriate transfer mechanism: the UK's International Data Transfer Agreement (IDTA), the UK Addendum to EU Standard Contractual Clauses, or rely on a UK adequacy regulation if one covers the destination country." },
      { type: "p", content: "Practical advice for procurement teams: ask for the IDTA. Read the appendices. Confirm the destination country has adequacy or that the SCCs/IDTA are signed and dated. If your supplier can't produce these in one email, that tells you something about how much they care." },
      { type: "h2", content: "What 'UK GDPR compliant' should mean on a vendor's website" },
      { type: "ul", content: [
        "A published privacy notice that names the controller, the data, the lawful basis and the retention period.",
        "A signed UK-flavoured DPA available on request, with the IDTA where international transfers happen.",
        "A clear sub-processor list with locations and roles.",
        "Demonstrable security measures (encryption at rest and in transit, role-based access, audit logs).",
        "Named DPO or named privacy contact, with a UK address.",
      ]},
      { type: "p", content: "If a vendor's site says 'GDPR compliant' but won't say which GDPR, or hosts your data 'somewhere in our global cloud', proceed with care." },
    ],
  },
  {
    slug: "civicsign-launch-15-field-types",
    title: "Product update: 15 field types now live in the Prepare Studio",
    excerpt: "Stamp, image, dropdown, radio, attachment and auto-filled identity fields are all live. Here's what each one does and which industries asked us for them.",
    category: "Product Updates",
    date: "Feb 13, 2026",
    readTime: "3 min read",
    author: "CivicSign Product",
    image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97",
    body: [
      { type: "p", content: "The Prepare Studio now ships with 15 field types out of the box. That covers every common UK signing scenario we've seen, and most of the uncommon ones. Here's the lineup and where each one earns its keep." },
      { type: "h2", content: "Signing fields" },
      { type: "ul", content: [
        "Signature, your headline event. Drawn, typed or uploaded.",
        "Initial, for paragraph-by-paragraph initialling on longer contracts.",
        "Sign date, auto-fills with today's date when the signer opens the document.",
      ]},
      { type: "h2", content: "Identity fields (auto-filled)" },
      { type: "p", content: "These pull from the recipient's email and profile data, the signer can correct them, but they shouldn't have to type them in." },
      { type: "ul", content: [
        "Full name, saves a typing step on every offer letter and tenancy agreement.",
        "Email, handy for double-confirming the address you're sending to.",
        "Company, useful on multi-party commercial contracts.",
        "Job title, used by HR, finance and supplier-onboarding flows.",
      ]},
      { type: "h2", content: "Form fields" },
      { type: "ul", content: [
        "Text, the workhorse free-text field.",
        "Date, any date, not just today's.",
        "Checkbox, single tick-box for opt-ins.",
        "Dropdown / Radio, guided choice. Senders type the placeholder for now; properly configurable option lists are coming next.",
      ]},
      { type: "h2", content: "Image-style fields" },
      { type: "ul", content: [
        "Stamp, the signer can upload a stamp image. Popular with surveyors and clinicians.",
        "Image, any signed-in image, e.g. a passport photo or proof-of-delivery snap.",
        "Attachment, the signer attaches a PDF or image to the envelope (e.g. ID document).",
      ]},
      { type: "h2", content: "Where they came from" },
      { type: "p", content: "Each field type came directly from customer requests. Stamp came from UK building surveyors. Image came from logistics. Dropdown and radio came from healthcare consent forms. Auto-filled identity fields came from HR teams tired of seeing 'PLEASE TYPE YOUR FULL LEGAL NAME HERE' filled with 'k'." },
      { type: "h2", content: "What's next" },
      { type: "ul", content: [
        "Configurable option lists for Dropdown and Radio fields, so senders can lock down the choices.",
        "Calculated fields (e.g. total of line-item fields), coming with our Stripe integration.",
        "Conditional fields that appear only when a previous answer matches.",
      ]},
      { type: "p", content: "All 15 field types are available on every plan today, including the free tier. If you've been waiting for a specific field to send a particular type of document, give it a try and let us know how it lands." },
    ],
  },
  {
    slug: "employment-contracts-electronic-signatures-uk",
    title: "Employment contracts and offer letters: e-signing in UK HR",
    excerpt: "Written statements of employment particulars, contracts and settlement agreements can all be executed electronically under English law. Here is what ACAS, GOV.UK and the tribunals expect from your audit trail.",
    category: "HR & People",
    date: "Feb 20, 2026",
    readTime: "7 min read",
    author: "CivicSign Editorial",
    image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40",
    body: [
      { type: "p", content: "Every UK employer must give employees and workers a written statement of employment particulars, a principal statement on day one and a wider written statement within two months. That document is not the same thing as the employment contract, but in practice most HR teams send both together. The question is not whether you can do this electronically. You can. The question is whether your signing process would stand up if a dispute reached an employment tribunal." },
      { type: "h2", content: "What the law actually requires" },
      { type: "p", content: "There is no general rule that employment contracts must be signed in wet ink. Under the Law Commission's 2019 report and section 7 of the Electronic Communications Act 2000, electronic signatures are admissible as evidence of authentication in UK courts, including employment tribunals. GOV.UK confirms that employers must provide the written statement on the first day of employment; it does not prescribe a paper delivery method." },
      { type: "ul", content: [
        "Principal statement, due on day one (employer name, job title, pay, hours, holiday, work location, probation and other day-one particulars).",
        "Wider written statement, due within two months (pensions, disciplinary and grievance procedures, collective agreements).",
        "Contract of employment, often signed alongside the statement; electronic execution is widely accepted for standard employment agreements.",
        "Settlement agreements, must be in writing and the employee must receive advice from a relevant independent adviser; electronic signing is permitted provided the statutory conditions are met.",
      ]},
      { type: "callout", content: "Tribunals care about evidence of agreement, not the colour of the ink. A typed name, drawn signature or click-to-sign all count as simple electronic signatures, provided you can prove who signed, when, and that the document was not altered afterwards." },
      { type: "h2", content: "What a tribunal-ready audit trail looks like" },
      { type: "p", content: "If an employee later claims they never received their contract, or that terms were changed after signing, your platform needs to answer four questions:" },
      { type: "ul", content: [
        "Who signed?, verified email address, ideally matched to the work or personal address you invited.",
        "When did they sign?, precise timestamps for sent, viewed and signed events.",
        "What did they sign?, a tamper-evident hash on the final PDF so any post-signature edit is detectable.",
        "Did they have a chance to read it?, a view event before the signature event on the audit trail.",
      ]},
      { type: "h2", content: "Practical HR flows that work" },
      { type: "ul", content: [
        "Pre-boarding: send the contract and written statement together before day one, the new starter signs electronically and arrives with paperwork already complete.",
        "Day-one essentials: if the contract went out early, send a short day-one pack (IT policy, expenses, handbook acknowledgement) as a second envelope.",
        "Contract variations: never edit a signed PDF by hand. Issue a variation letter, route it for signature, and keep both versions linked in the employee file.",
        "Leaver packs: settlement agreements and compromise agreements benefit from sequential signing, employee first, then the independent adviser's confirmation where required.",
      ]},
      { type: "h2", content: "Documents that still need extra care" },
      { type: "p", content: "Standard employment contracts are straightforward. Three categories need more thought:" },
      { type: "ul", content: [
        "Settlement agreements, the independent adviser must confirm they have advised the employee; build this into your signing order.",
        "Restrictive covenants in senior hires, some employers still prefer wet ink or witnessed execution for high-value roles, though electronic signatures are generally valid.",
        "Share schemes and EMI agreements, check your scheme rules; HMRC and company law requirements may specify additional execution formalities.",
      ]},
      { type: "p", content: "For the 95% of UK hiring that is offer letter, contract, handbook acknowledgement and policy attestation, electronic signing is not a shortcut, it is the sensible default. The employers who get into trouble are not the ones who sign electronically. They are the ones who cannot prove what was signed." },
    ],
  },
  {
    slug: "ast-agreements-electronic-signing-uk-lettings",
    title: "AST agreements by e-signature: what UK letting agents need to know",
    excerpt: "Assured Shorthold Tenancy agreements, guarantor deeds and deposit paperwork can all be signed electronically in England and Wales. Here is how to stay compliant with the Housing Act 1988 and Tenant Fees Act 2019.",
    category: "Real Estate",
    date: "Jan 05, 2026",
    readTime: "6 min read",
    author: "CivicSign Editorial",
    image: "https://images.unsplash.com/photo-1560185007-cde436f6a4d0",
    body: [
      { type: "p", content: "Letting agents used to chase tenants for wet-ink ASTs, guarantor deeds and inventory sign-offs. In 2026, most of that paperwork can be executed electronically, and the best agents have stopped apologising for it. Electronic signing is faster for tenants, cleaner for compliance files, and legally valid for standard tenancy agreements in England and Wales under the Law Commission's 2019 guidance." },
      { type: "h2", content: "What you can sign electronically" },
      { type: "ul", content: [
        "Assured Shorthold Tenancy (AST) agreements under the Housing Act 1988.",
        "Tenancy renewal and variation letters.",
        "Guarantor agreements (standard contracts, deeds of guarantee may need witnessing; check your template).",
        "Inventory and check-in / check-out reports.",
        "Permitted occupier and licence-to-occupy agreements.",
        "Agent terms of business with landlords.",
      ]},
      { type: "callout", content: "Section 21 and Section 8 notices have specific service requirements under the Housing Act 1988 and subsequent regulations. Electronic signing of the notice itself is one question; proving valid service to the tenant is another. Always check the latest court forms and guidance before switching notice workflows to electronic delivery." },
      { type: "h2", content: "Deposit and prescribed information" },
      { type: "p", content: "Under the Tenant Fees Act 2019 and the Housing Act 2004 (as amended), landlords must protect tenancy deposits in a government-approved scheme and provide prescribed information to the tenant within 30 days. That prescribed information can be delivered electronically. Pair it with the AST in a single signing envelope: tenant signs the tenancy, receives the deposit protection leaflet and prescribed information in the same flow, and your compliance file is complete from day one." },
      { type: "h2", content: "A typical letting flow" },
      { type: "ul", content: [
        "Agent prepares the AST template with pre-placed fields for tenant, landlord, rent, term and deposit.",
        "Tenant receives the signing link on their phone, signs the AST, initials key clauses, and confirms the move-in date.",
        "Guarantor receives a separate envelope (sequential or parallel, depending on your policy).",
        "Inventory is sent on check-in day; tenant signs on the spot with photos attached.",
        "Certificate of Completion and prescribed information are stored against the tenancy record.",
      ]},
      { type: "h2", content: "When to pause before going electronic" },
      { type: "p", content: "Not every property document is a straightforward AST:" },
      { type: "ul", content: [
        "Registered dispositions (transfers, charges), follow HM Land Registry Practice Guide 82, not general e-signature rules.",
        "Deeds of guarantee, if your guarantor deed is executed as a deed, witnessing requirements apply.",
        "Company lets where the tenant is a limited company, check whether your template requires a director signature in a particular form.",
        "Welsh tenancies, most standard occupation contracts can be signed electronically, but Wales has its own Renting Homes framework; use the correct Welsh forms.",
      ]},
      { type: "p", content: "For the high-volume work of UK lettings, ASTs, renewals, guarantors, inventories and agent terms, electronic signing is no longer a nice-to-have. It is how you stop losing tenants to competitors who send the paperwork in minutes, not days." },
    ],
  },
  {
    slug: "ses-aes-qes-which-signature-level-uk",
    title: "SES, AES or QES? Choosing the right UK eIDAS signature level",
    excerpt: "Not every contract needs a qualified signature, and most do not need a wet-ink stamp either. We explain when simple, advanced and qualified electronic signatures fit real UK business workflows, with plain-English examples.",
    category: "UK Law",
    date: "Mar 04, 2026",
    readTime: "8 min read",
    author: "CivicSign Editorial",
    image: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=1200&q=80",
    body: [
      { type: "p", content: "UK eIDAS recognises three tiers of electronic signature. Vendors love to sell the highest tier; lawyers love to warn about the lowest. The practical question for most British businesses is simpler: what evidence do you need if someone later denies they signed, or claims the document was altered? That answer maps cleanly onto SES, AES and QES, once you strip away the jargon." },
      { type: "h2", content: "Simple Electronic Signature (SES)" },
      { type: "p", content: "A simple electronic signature is any data attached to or logically associated with a document that the signer uses to sign. Under UK eIDAS Article 3(11), that includes typing your name, drawing on a touchscreen, uploading a signature image, or clicking an clearly labelled 'I agree' button. SES is legally valid for the overwhelming majority of UK commercial contracts." },
      { type: "ul", content: [
        "Best for: NDAs, sales quotes, order forms, consultancy agreements, tenancy paperwork, internal policy acknowledgements, and routine supplier terms.",
        "Evidence you need: signer identity (typically verified email), timestamps, IP address, and a record showing the document viewed before signing.",
        "CivicSign: SES is selectable on Pro when sending, with a full audit trail and Certificate of Completion on every envelope.",
      ]},
      { type: "h2", content: "Advanced Electronic Signature (AES)" },
      { type: "p", content: "An advanced electronic signature must be uniquely linked to the signer, capable of identifying them, created under their sole control, and linked to the data in a way that detects subsequent changes. UK eIDAS Article 26 sets the standard. AES is not magic, it is SES plus stronger identity binding and tamper detection built into the process." },
      { type: "ul", content: [
        "Best for: employment contracts, settlement agreements, high-value B2B contracts, regulated-industry paperwork, and any agreement where you expect a serious dispute.",
        "Extra assurance: stronger signer attribution, platform-level tamper detection, and optional SMS or knowledge-based authentication on Business plans.",
        "CivicSign: Pro users can select AES on Review & Send; Business defaults to AES with optional recipient authentication.",
      ]},
      { type: "callout", content: "Choosing AES is not an admission that SES is weak. It is a risk decision. If the cost of a dispute exceeds the cost of stronger evidence, AES is the sensible default, not because a judge demanded it upfront, but because your file needs to speak for itself." },
      { type: "h2", content: "Qualified Electronic Signature (QES)" },
      { type: "p", content: "A qualified electronic signature is an advanced signature backed by a qualified certificate issued by a Qualified Trust Service Provider (QTSP) listed on the UK trust list. QES carries a statutory presumption of validity equivalent to a handwritten signature in certain cross-border contexts. In domestic UK practice, QES is the exception, not the rule." },
      { type: "ul", content: [
        "Consider QES for: specific EU cross-border transactions, some public-sector tenders, and niche regulated workflows where a QTSP-backed certificate is contractually required.",
        "Usually unnecessary for: standard UK employment, lettings, NDAs, SaaS agreements, and SME supplier contracts.",
        "CivicSign: QES is available on request for Business customers via a QTSP partner, contact us if your counterparty or regulator mandates it.",
      ]},
      { type: "h2", content: "A decision table you can actually use" },
      { type: "ul", content: [
        "Low risk, high volume → SES with a solid audit trail.",
        "HR, legal, or financial exposure → AES.",
        "Counterparty or regulation names a QTSP → QES.",
        "Deed with HM Land Registry → follow Practice Guide 82 (platform process + conveyancer certificate), not generic SES/AES labels alone.",
      ]},
      { type: "h2", content: "What tribunals and courts actually scrutinise" },
      { type: "p", content: "UK courts rarely ask which eIDAS tier you picked. They ask whether the signer intended to be bound, whether they had access to the final text, and whether the document integrity can be demonstrated. A meticulous SES audit trail beats a sloppy AES process every time. Tier choice matters, but process quality matters more." },
      { type: "p", content: "Document your signing policy internally: which agreement types use SES, which default to AES, and who approves exceptions. When CivicSign appends a Certificate of Completion with timestamps, IP data and a SHA-256 seal, you are giving a future judge exactly the narrative they need, regardless of tier." },
    ],
  },
  {
    slug: "nda-confidentiality-agreements-electronic-signatures-uk",
    title: "NDAs and confidentiality agreements: signing electronically in the UK",
    excerpt: "Mutual NDAs, one-way confidentiality letters and contractor secrecy terms are among the fastest documents to send, and among the first challenged when a deal goes wrong. Here is how to make electronic NDAs stick.",
    category: "UK Law",
    date: "Mar 12, 2026",
    readTime: "6 min read",
    author: "CivicSign Editorial",
    image: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=1200&q=80",
    body: [
      { type: "p", content: "Every founder, agency and corporate deal team sends NDAs before sharing a pitch deck, cap table or product roadmap. Wet ink used to mean a two-day delay; in 2026 it mostly means someone prints a PDF at home and photographs it badly. Electronic NDAs are not a grey area, they are standard practice under English contract law, provided you can prove agreement and preserve document integrity." },
      { type: "h2", content: "Are electronic NDAs binding?" },
      { type: "p", content: "Yes. Confidentiality agreements are ordinary contracts. They require offer, acceptance, consideration (or execution as a deed where no consideration passes), and intention to create legal relations. None of those elements requires pen and paper. Section 7 of the Electronic Communications Act 2000 makes electronic signatures admissible as evidence of authentication in UK proceedings." },
      { type: "h2", content: "One-way vs mutual NDAs" },
      { type: "ul", content: [
        "One-way NDA: only the receiving party signs, route a single signature field and keep the disclosing party's details in the header.",
        "Mutual NDA: both parties sign, use parallel signing when both sides are ready, or sequential if your policy requires the initiator to sign first.",
        "Deed of confidentiality: rare in tech and agency work, but if your template is expressed as a deed, check witnessing requirements before sending electronically.",
      ]},
      { type: "callout", content: "Speed is a feature, not a legal risk, as long as the recipient sees the full NDA before signing. Always require a 'viewed' event on the audit trail before the signature event. That single timestamp often defeats 'I never saw clause 7' arguments." },
      { type: "h2", content: "Fields that belong on every NDA envelope" },
      { type: "ul", content: [
        "Full legal name and signing capacity (e.g. 'for and on behalf of Acme Ltd').",
        "Date field auto-populated at signature time.",
        "Initials on survival periods, non-solicit clauses and governing law if your counsel requires it.",
        "Email address matching the party you invited, not a forwarded link to an unknown inbox.",
      ]},
      { type: "h2", content: "Common mistakes we see in disputes" },
      { type: "ul", content: [
        "Sending a Word version for 'track changes' after the NDA is signed, issue a variation or a new envelope instead.",
        "Sharing the signing link in a public Slack channel, invite named recipients only.",
        "Using a personal Gmail for a company NDA without stating capacity, add a text field for title and entity.",
        "No audit trail exported when the dispute starts, export the Certificate of Completion on day one, not month six.",
      ]},
      { type: "p", content: "For most UK businesses, an electronically signed mutual NDA with CivicSign's audit trail is stronger than a scanned PDF nobody can authenticate. Send it in minutes, store the sealed PDF once, and move on to the term sheet." },
    ],
  },
  {
    slug: "audit-trail-certificate-of-completion-guide",
    title: "Building a tribunal-ready audit trail for electronic signatures",
    excerpt: "A signature image on a PDF is not evidence. A chronological audit trail with identity, consent, timestamps and a tamper-evident seal is. We break down every event your platform should record, and how to present it if challenged.",
    category: "Compliance",
    date: "Mar 19, 2026",
    readTime: "7 min read",
    author: "CivicSign Editorial",
    image: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=1200&q=80",
    body: [
      { type: "p", content: "When a contract dispute reaches a solicitor's desk, the first question is not 'did they use electronic signatures?' It is 'can you prove what happened?' The difference between winning and losing a paper trail argument is almost always the audit trail, not the signature font." },
      { type: "h2", content: "The minimum viable audit trail" },
      { type: "p", content: "Every credible UK e-signature platform should record at least the following events in order:" },
      { type: "ul", content: [
        "Envelope created, who prepared the document, when, and from which account.",
        "Sent, each recipient's email, routing order (sequential or parallel), and dispatch timestamp.",
        "Viewed, when the recipient opened the signing page (proves access to the text).",
        "Consent, explicit acceptance of electronic signing where your workflow requires it.",
        "Signed, method used (drawn, typed, uploaded), timestamp, and IP address.",
        "Completed, final PDF generated, hash computed, and copies delivered.",
      ]},
      { type: "h2", content: "Why the hash matters" },
      { type: "p", content: "SHA-256 sealing means any byte-level change to the completed PDF produces a different hash. You do not need a judge who understands cryptography, you need a report that says 'this file matches the sealed version' or 'this file has been altered.' CivicSign computes the hash at completion and references it on the Certificate of Completion appended to the document." },
      { type: "callout", content: "Export the Certificate of Completion at the moment of signing, not when litigation is threatened. Platforms log events in real time; your case file should mirror that discipline." },
      { type: "h2", content: "Identity: email is not enough on its own, but it is the foundation" },
      { type: "p", content: "Most UK SME workflows rely on verified email invitation plus IP and timestamp correlation. That is sufficient for thousands of contracts daily. For higher-risk agreements, layer SMS one-time codes or knowledge-based authentication (available on CivicSign Business) so the audit trail shows a second factor at signing time." },
      { type: "h2", content: "Presenting evidence to a solicitor or tribunal" },
      { type: "ul", content: [
        "Provide the final PDF with the Certificate of Completion attached, not a screenshot of the signing page.",
        "Include the envelope ID and hash in your bundle index.",
        "Chronology table: one row per audit event with UTC timestamps.",
        "Explain routing: if sequential signing was used, show why (e.g. witness after signatory).",
        "Retain the platform export for the limitation period relevant to the contract, not just until the project ends.",
      ]},
      { type: "h2", content: "Internal policy tip" },
      { type: "p", content: "Name an owner for envelope retention in each department. Sales owns customer order forms; HR owns contracts; Legal owns settlement agreements. When everyone uses the same platform but nobody owns exports, you discover gaps only after the dispute starts. A five-minute export habit beats a five-week disclosure fight." },
    ],
  },
  {
    slug: "freelancer-consultant-contracts-e-signing-uk",
    title: "Freelancer and consultant contracts: e-signing for UK sole traders",
    excerpt: "IR35 status letters, statements of work, IP assignments and payment terms can all be executed electronically. Here is a practical signing workflow for agencies, founders and freelancers who are tired of chasing PDFs.",
    category: "HR & People",
    date: "Mar 26, 2026",
    readTime: "6 min read",
    author: "CivicSign Editorial",
    image: "https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?w=1200&q=80",
    body: [
      { type: "p", content: "The UK freelance economy runs on contracts that are often one or two pages long, and delayed for days because someone is 'on a train' without a printer. Electronic signing fixes the logistics without changing the law. Whether you are a sole trader accepting a statement of work or an agency onboarding fifty contractors a month, the same rules apply: capture intent, identity and a clean final PDF." },
      { type: "h2", content: "Documents freelancers sign every week" },
      { type: "ul", content: [
        "Statements of work and master services agreements.",
        "Non-disclosure and confidentiality terms.",
        "Intellectual property assignment and moral rights waivers.",
        "Data processing agreements when the freelancer handles personal data.",
        "Status determination statements and IR35-related paperwork (keep HMRC guidance in mind for the substance of the determination, not the signing method).",
        "Invoice authorisation and change-order confirmations.",
      ]},
      { type: "h2", content: "Sole trader vs limited company" },
      { type: "p", content: "When contracting with a limited company, the signature block should name the entity and the signatory's capacity ('Director'). For sole traders, the individual's legal name is sufficient. Electronic platforms do not remove the need for correct capacity, they make it easier to enforce once the block is right." },
      { type: "callout", content: "Send the contract and the SOW in one envelope when possible. One audit trail, one completion date, one file for your accountant at year-end." },
      { type: "h2", content: "A 10-minute onboarding flow" },
      { type: "ul", content: [
        "Upload your standard MSA template with fields pre-placed.",
        "Duplicate as an envelope per contractor, swap name, rate, start date and IR35 status fields only.",
        "Use parallel signing when both parties must sign the MSA; use recipient-only signing for one-way SOWs.",
        "Store the completed PDF in your project folder with the envelope ID in the filename.",
      ]},
      { type: "h2", content: "When clients push back" },
      { type: "p", content: "Some enterprise procurement teams still ask for wet ink out of habit. Point them to the Law Commission's 2019 report and your platform's Certificate of Completion. Offer AES on Business-tier workflows if they want stronger identity binding. In practice, most pushback collapses once legal reviews the audit trail sample, not the signature graphic." },
    ],
  },
  {
    slug: "supplier-contracts-purchase-orders-electronic-signatures-uk",
    title: "Supplier contracts and purchase orders: electronic signing for UK procurement",
    excerpt: "Chasing a purchase order signature should not take longer than delivering the goods. How UK operations and finance teams use e-signatures for supplier onboarding, framework agreements and order confirmations.",
    category: "Compliance",
    date: "Apr 02, 2026",
    readTime: "7 min read",
    author: "CivicSign Editorial",
    image: "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=1200&q=80",
    body: [
      { type: "p", content: "Procurement teams live in email threads named 'FINAL_v7_PO_signed(1).pdf'. Electronic signing replaces that chaos with a single sealed document and a timestamp everyone can agree on. For UK supply chains, electronic execution of purchase orders, framework agreements and standard terms is legally straightforward, the operational win is speed and version control." },
      { type: "h2", content: "What procurement can sign electronically" },
      { type: "ul", content: [
        "Standard terms and conditions of purchase.",
        "Framework agreements and call-off contracts.",
        "Purchase orders above delegated authority thresholds.",
        "Supplier onboarding packs: bank details form, anti-bribery declaration, modern slavery statement acknowledgement.",
        "Variation orders and change notes to existing supply agreements.",
      ]},
      { type: "h2", content: "Delegation and authority" },
      { type: "p", content: "Electronic signing does not bypass your internal authority matrix. If only a director may commit the company above £50,000, route the envelope to the director's verified work email and record their signature on the audit trail. Platforms make delegation visible; they do not replace corporate governance." },
      { type: "callout", content: "Version control is a legal issue. Never resend a 'quickly edited' PO over email after partial signatures. Void the envelope, issue a new one, and keep one completion event per order." },
      { type: "h2", content: "Matching finance systems" },
      { type: "ul", content: [
        "Include PO number, cost centre and delivery date as pre-filled text fields.",
        "Require supplier signature on acceptance of terms, not just an email reply.",
        "Export the Certificate of Completion to your ERP or shared drive the same day, finance audits love timestamps that precede goods receipt.",
        "On Business plans, use webhooks to notify your procurement system when an envelope completes (no manual chasing).",
      ]},
      { type: "h2", content: "Cross-border suppliers" },
      { type: "p", content: "UK law governs many of your domestic supplier agreements regardless of where the supplier is based. For EU suppliers post-Brexit, confirm governing law and whether the counterparty's legal team expects QES, rare for routine POs, more common in regulated supply. Default to AES when the contract value or regulatory exposure justifies it." },
    ],
  },
  {
    slug: "settlement-agreements-electronic-signing-uk-hr",
    title: "Settlement agreements by e-signature: what UK HR teams must get right",
    excerpt: "Settlement agreements must be in writing and the employee must receive independent legal advice. Electronic execution is permitted, but the signing order, adviser's role and audit trail need extra care.",
    category: "HR & People",
    date: "Apr 10, 2026",
    readTime: "8 min read",
    author: "CivicSign Editorial",
    image: "https://images.unsplash.com/photo-1521791136064-7986c2920216?w=1200&q=80",
    body: [
      { type: "p", content: "Settlement agreements (formerly compromise agreements) are among the most sensitive documents HR handles. They must satisfy section 203 of the Employment Rights Act 1996: in writing, relate to the particular proceedings, and confirm that an independent adviser has explained the terms and effect. Electronic signing does not relax any of those requirements, it only changes how ink appears on the page." },
      { type: "h2", content: "Statutory conditions still apply" },
      { type: "ul", content: [
        "The agreement must be in writing, a completed PDF with signatures satisfies this.",
        "The employee must receive advice from a relevant independent adviser (solicitor, certified trade union official, or advice centre worker with appropriate insurance).",
        "The adviser must sign a certificate confirming advice was given, build this into your envelope order.",
        "The employee's signature must be informed, allow viewing time on the audit trail before signing.",
      ]},
      { type: "callout", content: "Never pressure same-day signing on a settlement agreement. Tribunals scrutinise undue haste. A 24–48 hour viewing window between send and signature is prudent HR practice, even when the platform allows instant completion." },
      { type: "h2", content: "Recommended signing sequence" },
      { type: "ul", content: [
        "Employer sends draft to employee's personal email (not only work email if access may be withdrawn).",
        "Employee reviews and signs, or signs after adviser meeting.",
        "Independent adviser signs adviser certificate block (name, firm, date).",
        "Employer counter-signs last, payment trigger often tied to this event.",
      ]},
      { type: "h2", content: "AES vs SES for settlements" },
      { type: "p", content: "Many employers use AES (or AES with SMS authentication) for settlement agreements because the evidential bar is higher if the employee later claims duress or lack of advice. CivicSign Pro allows AES selection on send; Business adds optional recipient authentication. The adviser certificate should still be a wet or electronic signature from a regulated individual, not an automated stamp." },
      { type: "h2", content: "Records to retain" },
      { type: "ul", content: [
        "Final signed PDF with Certificate of Completion.",
        "Adviser's certificate and evidence of their qualifications.",
        "Communication showing the employee chose the adviser (or was given time to do so).",
        "Payment confirmation tied to the employer's counter-signature date.",
      ]},
      { type: "p", content: "Done properly, electronic settlement agreements are faster for leavers and cleaner for HR files. Done hastily, they become expensive litigation. The platform gives you the audit trail; your process gives it meaning." },
    ],
  },
  {
    slug: "electronic-signatures-construction-contracts-uk",
    title: "JCT and construction contracts: electronic signing on UK building projects",
    excerpt: "Main contracts, collateral warranties and subcontractor appointments are increasingly executed electronically on UK sites. What quantity surveyors, contractors and subcontractors should verify before clicking sign.",
    category: "Real Estate",
    date: "Apr 18, 2026",
    readTime: "7 min read",
    author: "CivicSign Editorial",
    image: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=1200&q=80",
    body: [
      { type: "p", content: "Construction runs on paper, or it used to. JCT contracts, NEC4 options, subcontractor orders and collateral warranties are now routinely signed from site offices and quantity surveyors' laptops. UK law treats them like any other contract: electronic signatures are valid if execution formalities are met and the audit trail is sound." },
      { type: "h2", content: "Documents commonly signed electronically" },
      { type: "ul", content: [
        "Subcontract orders and domestic subcontracts.",
        "Variations and change instructions.",
        "Collateral warranties for funders and purchasers.",
        "Practical completion certificates and snagging sign-offs.",
        "RAMS acknowledgements and site induction declarations.",
        "Consultant appointments under standard form agreements.",
      ]},
      { type: "h2", content: "Deeds and witnessing" },
      { type: "p", content: "Some construction documents are executed as deeds, collateral warranties frequently are. Deeds require witnessing under English law. Electronic witnessing is permitted in many commercial contexts under the Law Commission's analysis, but practical arrangements matter: the witness should be physically present when the signatory applies their electronic signature, and the witness should sign immediately after in the same envelope where possible." },
      { type: "callout", content: "Use sequential signing for deed workflows: signatory first, witness second, then any employer counter-signature. Parallel routing invites witness-before-signatory errors that invalidate the deed." },
      { type: "h2", content: "Site practicalities" },
      { type: "ul", content: [
        "Subcontractors often sign on mobile, ensure signature fields are large enough and the PDF is legible on a phone screen.",
        "Pre-fill project name, contract sum and retention percentage as locked text before send.",
        "Attach drawings and specifications as part of the envelope record, not as a separate email that might not match the signed order.",
        "Store completed PDFs against the project WBS code finance already uses.",
      ]},
      { type: "h2", content: "When the funder asks for wet ink" },
      { type: "p", content: "Some funders and developers still specify wet-ink collateral warranties in facility agreements written years ago. That is a commercial requirement in the finance documents, not a statement of general UK law. Negotiate electronic acceptance with reference to current Law Society and HM Land Registry practice, or use electronic signing for subcontract tiers while reserving wet ink only where the funder insists." },
    ],
  },
  {
    slug: "electronic-signatures-healthcare-consent-uk",
    title: "Patient consent forms and healthcare paperwork: e-signatures in the UK",
    excerpt: "Treatment consent, privacy notices and staff employment documents in UK healthcare settings can often be signed electronically, with strict UK GDPR, CQC and clinical governance requirements alongside.",
    category: "Compliance",
    date: "Apr 25, 2026",
    readTime: "7 min read",
    author: "CivicSign Editorial",
    image: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=1200&q=80",
    body: [
      { type: "p", content: "Healthcare organisations generate enormous volumes of consent and governance paperwork. Electronic signing can reduce waiting-room friction and improve record-keeping, but clinical and data-protection requirements come first. This article addresses UK GP practices, dental clinics, private providers and NHS-aligned services using e-signatures responsibly." },
      { type: "h2", content: "What can typically be signed electronically" },
      { type: "ul", content: [
        "Privacy notices and UK GDPR privacy acknowledgements.",
        "Consent to routine treatment where English common law and GMC guidance expect documented consent (not a substitute for the conversation itself).",
        "Staff contracts, policies and mandatory training attestations.",
        "Supplier and locum clinician agreements.",
        "Photo and marketing consent where appropriate.",
      ]},
      { type: "h2", content: "UK GDPR and special category data" },
      { type: "p", content: "Health data is special category data under UK GDPR Article 9. Using an e-signature platform means choosing a UK-appropriate processor with encryption in transit, access controls and a clear Data Processing Agreement. CivicSign is UK-owned and UK-hosted, a meaningful distinction when patient identifiers appear on consent forms." },
      { type: "callout", content: "Electronic consent records the patient's agreement to a documented explanation, it does not replace the clinician's duty to explain the procedure, risks and alternatives. Document the conversation in the clinical record; use the e-signature as the patient's confirmation they received that information." },
      { type: "h2", content: "CQC and record-keeping" },
      { type: "ul", content: [
        "Completed consent PDFs should be filed in the patient record system with envelope ID and date.",
        "Audit trails should be exportable for CQC inspection without platform login barriers.",
        "Version control: if treatment plan changes materially, issue a new consent, do not annotate a signed PDF manually.",
        "Retention periods follow NHS and professional body guidance, not 'delete when the patient leaves'.",
      ]},
      { type: "h2", content: "Accessibility in waiting rooms" },
      { type: "p", content: "Offer patients who struggle with digital interfaces a supported option, staff-assisted signing on a clinic tablet, or paper with later scanning if necessary. Equality Act 2010 duties apply to how you deploy technology, not just whether signatures are electronic." },
    ],
  },
];

export const CATEGORIES = ["All", "UK Law", "Real Estate", "Charities", "HR & People", "Compliance", "Product Updates"];

export const getPost = (slug) => POSTS.find((p) => p.slug === slug);

/** Merge API payload over static fallback so new bundled posts work before DB seed. */
export function mergeStaticPost(slug, apiPost) {
  const fallback = getPost(slug);
  if (!apiPost) return fallback ?? null;
  if (!fallback) return apiPost;
  const body = Array.isArray(apiPost.body) && apiPost.body.length > 0 ? apiPost.body : fallback.body;
  return {
    ...fallback,
    ...apiPost,
    slug: apiPost.slug || fallback.slug,
    title: apiPost.title || fallback.title,
    excerpt: apiPost.excerpt || fallback.excerpt,
    category: apiPost.category || fallback.category,
    image: apiPost.image || fallback.image,
    author: apiPost.author || fallback.author,
    date: apiPost.date || fallback.date,
    readTime: apiPost.readTime || apiPost.read_time || fallback.readTime,
    body,
  };
}

export const getRelatedPosts = (slug, limit = 2, posts = POSTS) => {
  const current = posts.find((p) => p.slug === slug);
  if (!current) return [];
  return posts
    .filter((p) => p.slug !== slug)
    .sort((a, b) => (a.category === current.category ? -1 : 1) - (b.category === current.category ? -1 : 1))
    .slice(0, limit);
};

// API-merged list: returns static posts with admin-created posts overlaid.
// Used by the public /blog and /blog/:slug pages.
export async function fetchAllPosts() {
  try {
    const { data } = await api.get("/blog/posts");
    const apiBySlug = new Map(data.map((p) => [p.slug, p]));
    const merged = [...POSTS.map((p) => mergeStaticPost(p.slug, apiBySlug.get(p.slug)) || p)];
    for (const p of data) {
      if (!merged.find((x) => x.slug === p.slug)) merged.unshift(mergeStaticPost(p.slug, p) || p);
    }
    return merged;
  } catch {
    return POSTS;
  }
}

export async function fetchPost(slug) {
  const fallback = getPost(slug);
  try {
    const { data } = await api.get(`/blog/posts/${slug}`);
    return mergeStaticPost(slug, data) || fallback || null;
  } catch {
    return fallback ?? null;
  }
}
